apiVersion: v1
kind: Service
metadata:
  name: frontend-laravel
  labels:
    app: frontend-laravel
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: frontend-laravel
    tier: frontend
