apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: frontend-laravel
  labels:
    app: frontend-laravel
spec:
  selector:
    matchLabels:
      app: frontend-laravel
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-laravel
        tier: frontend
    spec:
      volumes:
        - name: var-run-volume
          emptyDir: {}

      containers:
        - name: nginx
          image: ${ECR_REPOSITORY_FRONTEND_NGINX_URL}:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
          volumeMounts:
            - name: var-run-volume
              mountPath: /var/run

        - name: php
          image: ${ECR_REPOSITORY_FRONTEND_PHP_URL}:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: var-run-volume
              mountPath: /var/run
