apiVersion: v1
kind: Service
metadata:
  name: api-laravel
  labels:
    app: api-laravel
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: api-laravel
    tier: backend
