version: "3"
services:
  api-php:
    build:
      context: ./api-laravel
      dockerfile: Dockerfile.api-php
    container_name: api-php
    volumes:
      - api-php-fpm-socket-volume:/var/run
    links:
      - db
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"

  api-db:
    build:
      context: ./api-laravel
      dockerfile: ./docker.api-db/Dockerfile.api-db
      env_file: ./docker.api-db/.env

    # environment:
    #   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #   MYSQL_DATABASE: ${MYSQL_DATABASE}
    #   MYSQL_USER: ${MYSQL_USER}
    #   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: api-db
    ports:
      - "3306:3306"

  api-nginx:
    build:
      context: ./api-laravel
      dockerfile: ./docker/Dockerfile.api-nginx
    container_name: api-nginx
    ports:
      - "9000:80"
    volumes:
      - api-php-fpm-socket-volume:/var/run

  php:
    build:
      context: ./
      dockerfile: Dockerfile.php
    container_name: php
    volumes:
      - php-fpm-socket-volume:/var/run
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - php-fpm-socket-volume:/var/run

volumes:
  ? php-fpm-socket-volume
  ? api-php-fpm-socket-volume
