version: "3"
services:
  api-php:
    build:
      context: ./api-laravel
      dockerfile: ./docker.api-php/Dockerfile.api-php
    container_name: api-php
    volumes:
      - api-php-fpm-socket-volume:/var/run
    links:
      - api-db
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=api-db"

  api-nginx:
    build:
      context: ./api-laravel
      dockerfile: ./docker.api-nginx/Dockerfile.api-nginx
    container_name: api-nginx
    ports:
      - "9000:80"
    volumes:
      - api-php-fpm-socket-volume:/var/run

  api-db:
    build:
      context: ./api-laravel
      dockerfile: ./docker.api-db/Dockerfile.api-db
    env_file: ./api-laravel//docker.api-db/.env
    container_name: api-db

  frontend-php:
    build:
      context: ./frontend-laravel
      dockerfile: ./docker.php/Dockerfile.php
    container_name: frontend-php
    volumes:
      - php-fpm-socket-volume:/var/run

  frontend-nginx:
    build:
      context: ./frontend-laravel
      dockerfile: ./docker.nginx/Dockerfile.nginx
    container_name: frontend-nginx
    ports:
      - "8080:80"
    volumes:
      - php-fpm-socket-volume:/var/run

volumes:
  ? php-fpm-socket-volume
  ? api-php-fpm-socket-volume
