version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - php:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: ./php
    volumes:
      - php:/var/www/html
      - ../proj:/var/www/html
    container_name: php
    links:
      - db
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: crud
      MYSQL_DATABASE: crud
      MYSQL_USER: crud
      MYSQL_PASSWORD: crud
    container_name: db
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  ? php
