version: "3"
services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - php-fpm-socket:/var/run
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: ./php
    container_name: php
    volumes:
      - ../proj:/var/www/html
      - php-fpm-socket:/var/run
      - ./php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    links:
      - db
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: crud
      MYSQL_DATABASE: crud
      MYSQL_USER: crud
      MYSQL_PASSWORD: crud
    container_name: db
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  ? www-data
  ? php-fpm-socket
