kind: Pod
apiVersion: v1
metadata:
  name: frontend-pod
  labels:
    app: score-app
    tier: frontend
spec:
  volumes:
    # Create the shared files volume to be used in both pods
    - name: shared-files
      emptyDir: {}

    # Add the ConfigMap we declared above as a volume for the pod
    # - name: nginx-config-volume
    #   configMap:
    #     name: nginx-config

  containers:
    - image: 185555976764.dkr.ecr.us-east-1.amazonaws.com/laravel-k83_php

      name: php
      volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
      # Important! After this container has started, the PHP files
      # in our Docker image aren't in the shared volume. We need to
      # get them into the shared volume. If we tried to write directly
      # to this volume from our Docker image the files wouldn't appear
      # in the nginx container.
      #
      # So, after the container has started, copy the PHP files from this
      # container's local filesystem (/app -- added via the Docker image)
      # to the shared volume, which is mounted at /var/www/html.
      # lifecycle:
      #   postStart:
      #     exec:
      #       command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html"]

    - image: 185555976764.dkr.ecr.us-east-1.amazonaws.com/laravel-k83_nginx
      name: nginx
      volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
        # - name: nginx-config-volume
        #   mountPath: /etc/nginx/nginx.conf
        #   subPath: nginx.conf
